# -*- coding: utf-8 -*-

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from PyQt5.QtWidgets import QFileDialog



class Ui_MainWindow(object):
    def setupUi(self, MainWindow, project):
        self.project = project
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 410, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 410, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 20, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 100, 141, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 55, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 220, 141, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 55, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 130, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 280, 51, 31))
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 280, 61, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 160, 141, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(90, 190, 141, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 20, 201, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(510, 20, 71, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(310, 50, 201, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(510, 50, 71, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(310, 80, 201, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(510, 80, 71, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 110, 201, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(510, 110, 71, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(310, 140, 201, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(510, 140, 71, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(310, 170, 201, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(510, 170, 71, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(310, 200, 201, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(510, 200, 71, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(310, 230, 201, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(510, 230, 71, 22))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(310, 260, 201, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(510, 260, 71, 22))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(310, 290, 201, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(510, 290, 71, 22))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(310, 320, 201, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(510, 320, 71, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(310, 350, 201, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(510, 350, 71, 22))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(310, 380, 201, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(510, 380, 71, 22))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(310, 420, 191, 16))
        self.label_20.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(510, 410, 71, 31))
        self.label_21.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:rgb(255, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 280, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionw1 = QtWidgets.QAction(MainWindow)
        self.actionw1.setObjectName("actionw1")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Export to CSV", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "AddToDB", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "Open Project", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("MainWindow", "New Project", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Nr. Bloc", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Tip Edificiu", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Oras", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Sector", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Strada", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Cladiri de locuit", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Cladiri social-culturale", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Cladiri industriale", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Anul", None, -1))
        self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "1990", None, -1))
        self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1991", None, -1))
        self.comboBox_2.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "1992", None, -1))
        self.comboBox_2.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "1993", None, -1))
        self.comboBox_2.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "1994", None, -1))
        self.comboBox_2.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "1995", None, -1))
        self.comboBox_2.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "1996", None, -1))
        self.comboBox_2.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "1997", None, -1))
        self.comboBox_2.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "1998", None, -1))
        self.comboBox_2.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "1999", None, -1))
        self.comboBox_2.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "2000", None, -1))
        self.comboBox_2.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "2001", None, -1))
        self.comboBox_2.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "2002", None, -1))
        self.comboBox_2.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "2003", None, -1))
        self.comboBox_2.setItemText(14, QtWidgets.QApplication.translate("MainWindow", "2004", None, -1))
        self.comboBox_2.setItemText(15, QtWidgets.QApplication.translate("MainWindow", "2005", None, -1))
        self.comboBox_2.setItemText(16, QtWidgets.QApplication.translate("MainWindow", "2006", None, -1))
        self.comboBox_2.setItemText(17, QtWidgets.QApplication.translate("MainWindow", "2007", None, -1))
        self.comboBox_2.setItemText(18, QtWidgets.QApplication.translate("MainWindow", "2008", None, -1))
        self.comboBox_2.setItemText(19, QtWidgets.QApplication.translate("MainWindow", "2009", None, -1))
        self.comboBox_2.setItemText(20, QtWidgets.QApplication.translate("MainWindow", "2010", None, -1))
        self.comboBox_2.setItemText(21, QtWidgets.QApplication.translate("MainWindow", "2011", None, -1))
        self.comboBox_2.setItemText(22, QtWidgets.QApplication.translate("MainWindow", "2012", None, -1))
        self.comboBox_2.setItemText(23, QtWidgets.QApplication.translate("MainWindow", "2013", None, -1))
        self.comboBox_2.setItemText(24, QtWidgets.QApplication.translate("MainWindow", "2014", None, -1))
        self.comboBox_2.setItemText(25, QtWidgets.QApplication.translate("MainWindow", "2015", None, -1))
        self.comboBox_2.setItemText(26, QtWidgets.QApplication.translate("MainWindow", "2016", None, -1))
        self.comboBox_2.setItemText(27, QtWidgets.QApplication.translate("MainWindow", "2017", None, -1))
        self.comboBox_2.setItemText(28, QtWidgets.QApplication.translate("MainWindow", "2018", None, -1))
        self.comboBox_2.setItemText(29, QtWidgets.QApplication.translate("MainWindow", "2019", None, -1))
        self.comboBox_2.setItemText(30, QtWidgets.QApplication.translate("MainWindow", "2020", None, -1))
        self.comboBox_3.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Chisinau", None, -1))
        self.comboBox_3.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Balti", None, -1))
        self.comboBox_3.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Orhei", None, -1))
        self.comboBox_3.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Tiraspol", None, -1))
        self.comboBox_3.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "Ribnita", None, -1))
        self.comboBox_4.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "centru", None, -1))
        self.comboBox_4.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "nord", None, -1))
        self.comboBox_4.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "sud", None, -1))
        self.comboBox_4.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "vest", None, -1))
        self.comboBox_4.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "est", None, -1))
        self.comboBox_4.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Botanica", None, -1))
        self.comboBox_4.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "Buiucani", None, -1))
        self.comboBox_4.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "Centru", None, -1))
        self.comboBox_4.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "Ciocana", None, -1))
        self.comboBox_4.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "Rascani", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Valoarea pozitiei geografice", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Starea terenului amplasarii", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Poluarea mediului", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Zgomotul inconjurator", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Calitatea materialului constructiei", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Grosimea peretilor", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Calitatea acoperisului", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Calitatea peretilor", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Securitatea la incendiu", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Nivelul de ruinare", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Calitatea geamurilor", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Rezistenta mecanica", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Stabilitatea blocului", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Valoarea Proiectului", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "Randomize", None, -1))
        self.actionw1.setText(QtWidgets.QApplication.translate("MainWindow", "w1", None, -1))
       
        MainWindow.setWindowTitle("Analiza Multicriteriala")
        self.pushButton_3.clicked.connect(self.project.openProjectClick)
        self.pushButton_4.clicked.connect(self.project.selectNewProject)
        self.pushButton_5.clicked.connect(self.project.randomize)


    def afisareFactori(self, factori, importanta):
        self.lineEdit_6.setText(str(factori.valoarea_pozitiei_geografice))
        self.lineEdit_7.setText(str(factori.starea_terenului_amplasarii))
        self.lineEdit_8.setText(str(factori.poluarea_mediului))
        self.lineEdit_9.setText(str(factori.zgomotul_inconjurator))
        self.lineEdit_10.setText(str(factori.calitatea_materialului_constructiei))
        self.lineEdit_11.setText(str(factori.grosimea_peretilor))
        self.lineEdit_12.setText(str(factori.calitatea_acoperisului))
        self.lineEdit_13.setText(str(factori.calitatea_peretilor))
        self.lineEdit_14.setText(str(factori.securitatea_la_incendiu))
        self.lineEdit_15.setText(str(factori.nivelul_de_ruinare))
        self.lineEdit_16.setText(str(factori.calitatea_geamurilor))
        self.lineEdit_17.setText(str(factori.rezistenta_mecanica))
        self.lineEdit_18.setText(str(factori.stabilitatea_blocului))

        vp = (float(factori.valoarea_pozitiei_geografice) + (importanta.importantaFactorului1 / 100) + \
              float(factori.starea_terenului_amplasarii) + (importanta.importantaFactorului2 / 100) + \
              float(factori.poluarea_mediului) + (importanta.importantaFactorului3 / 100) + \
              float(factori.zgomotul_inconjurator) + (importanta.importantaFactorului4 / 100) + \
              float(factori.calitatea_materialului_constructiei) + (importanta.importantaFactorului5 / 100) + \
              float(factori.grosimea_peretilor) + (importanta.importantaFactorului6 / 100) + \
              float(factori.calitatea_acoperisului) + (importanta.importantaFactorului7 / 100) + \
              float(factori.calitatea_peretilor) + (importanta.importantaFactorului8 / 100) + \
              float(factori.securitatea_la_incendiu) + (importanta.importantaFactorului9 / 100) + \
              float(factori.nivelul_de_ruinare) + (importanta.importantaFactorului10 / 100) + \
              float(factori.calitatea_geamurilor) + (importanta.importantaFactorului11 / 100) + \
              float(factori.rezistenta_mecanica) + (importanta.importantaFactorului12 / 100) + \
              float(factori.stabilitatea_blocului) + (importanta.importantaFactorului13 / 100)) / 13
        self.label_21.setText(str(vp))

    def setAllToDefault(self):
        self.lineEdit.setText("")
        self.comboBox.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_4.setCurrentIndex(0)
        self.lineEdit_5.setText("")
        self.comboBox_2.setCurrentIndex(0)
        self.lineEdit_6.setText("")
        self.lineEdit_7.setText("")
        self.lineEdit_8.setText("")
        self.lineEdit_9.setText("")
        self.lineEdit_10.setText("")
        self.lineEdit_11.setText("")
        self.lineEdit_12.setText("")
        self.lineEdit_13.setText("")
        self.lineEdit_14.setText("")
        self.lineEdit_15.setText("")
        self.lineEdit_16.setText("")
        self.lineEdit_17.setText("")
        self.lineEdit_18.setText("")
        self.label_21.setText("")

    def setFactoriToDefault(self):
        self.lineEdit_6.setText("")
        self.lineEdit_7.setText("")
        self.lineEdit_8.setText("")
        self.lineEdit_9.setText("")
        self.lineEdit_10.setText("")
        self.lineEdit_11.setText("")
        self.lineEdit_12.setText("")
        self.lineEdit_13.setText("")
        self.lineEdit_14.setText("")
        self.lineEdit_15.setText("")
        self.lineEdit_16.setText("")
        self.lineEdit_17.setText("")
        self.lineEdit_18.setText("")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
